import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} dark`}>
      <body className="bg-zinc-950 text-zinc-50 antialiased selection:bg-blue-500/30">
        <nav className="p-6 border-b border-zinc-800 flex justify-between items-center max-w-5xl mx-auto">
          <span className="font-bold text-xl tracking-tighter">NIHAD.</span>
          <div className="space-x-6 text-sm font-medium text-zinc-400">
            <div className="space-x-6 text-sm font-medium text-zinc-400">
              <Link href="/" className="hover:text-white transition">Home</Link>
              <Link href="/about" className="hover:text-white transition">About</Link>
              <Link href="/projects" className="hover:text-white transition">Projects</Link>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
